/**
 * 合约地址配置
 * @generated by hardhat（DO NOT MODIFY!!!）
 */
export const addressConfig = {
  mockERC20: '0xbf79e18885c52BA7be82444cBAc2E4d0F1f6a5f6',
  mockUSDC: '0x09741B204231A19f9032fEA5f1C2C6f606BfBF36',
  mockUniswapV2Pair: '0x23083DE019bCa7280535EF5eB1bE359B18101ab5',
}
