/**
 * 合约地址配置
 * @generated by hardhat（DO NOT MODIFY!!!）
 */
export const addressConfig = {
  mockERC20: '0x3a0BA579f498707f0E492fA06E402467001d56cB',
  mockUSDC: '0x2C7f33c1cDFc642ab44FDcb8A351a73c701fE51B',
  mockUniswapV2Pair: '0xcB6b7e3AfD03993fe8f08843d5605ddB1a59E942',
}
