/**
 * 合约地址配置
 * @generated by hardhat（DO NOT MODIFY!!!）
 */
export const addressConfig = {
  mockERC20: '0xF9eE0D2efc7871265B9466092cA4c6adf98f8013',
  mockUSDC: '0x6734eD8F0cD4C564EAc357fF14da6d784417cB0D',
  mockUniswapV2Pair: '0x54414427ea95b793a2717cb884955D2Dbd0AE816',
}
