name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install contract dependencies
        working-directory: contracts
        run: npm ci

      - name: Generate contract types
        working-directory: contracts
        run: npm run typechain

      # - name: Run linting
      #   run: npm run lint

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
